### ISSUE TITLE
No file exist with name movies.js in routes as mentioned in Readme.md

### ISSUE THREAD

**Issue by shivarajnaidu** [davidgatti/How-to-Stream-Movies-using-NodeJS#2]
The current Readme.md file looks like 

> This is a very quick and easy article explaining how to stream movies to an HTML 5 video tag using NodeJS. The whole project is very small and compact. Focus your attention on the **movie.js** file in the routes folder.

But there is no file named movies.js in routes..
Only video.js is there ...
Please update Readme.md file with correct information..

**Comment by davidgatti** [comment]
Done :)
