### ISSUE TITLE
Running the project

### ISSUE THREAD

**Issue by ajibdeji** [davidgatti/How-to-Stream-Movies-using-NodeJS#6]
How do we run this project on localhost?

**Comment by davidgatti** [comment]
Like any other NodeJS project:

- npm install
- nom start

**Comment by ajibdeji** [comment]
<img width="443" alt="gitstream" src="https://user-images.githubusercontent.com/8040889/28885090-83ca39d6-7782-11e7-8646-cd197da5ed09.PNG">
<img width="436" alt="gitstream2" src="https://user-images.githubusercontent.com/8040889/28885089-839e9dda-7782-11e7-9fd5-2456c8c872f1.PNG">

I get the following errors

**Comment by davidgatti** [comment]
As the highlighted text say, you are missing the .env file :) 

You can install [env-auto](https://www.npmjs.com/package/env-auto) globally and then run it in the project folder. It should generate a .env file for you.

Or you can check the `app.json` file and see what environment variables are needed, and make the file by hand.

If you want to learn more you can check out the [foreman](https://www.npmjs.com/package/foreman) module.

**Comment by ajibdeji** [comment]
![image](https://user-images.githubusercontent.com/8040889/28930895-57a82bf4-7842-11e7-8ee8-9a9f004fc9d6.png)
 Still I get that error. Cant I just specify a port and access directly?

**Comment by ajibdeji** [comment]
I am sorry for all the issues, I am a bit rusty with nodejs as I am a newbie

**Comment by davidgatti** [comment]
OK, got it, this project is meant to be run under Linux and you are using Windows :) I'm using a Bash script to make a decision how to run the server. 

Sadly I have no idea how to run a NodeJS project on Windows. I would recommend using a Linux box.

**Comment by ajibdeji** [comment]
Is there a way I can just specify it uses a port with express and then just run it directly, removing all the usage of environmental variables

**Comment by davidgatti** [comment]
You should be able to do this:

`PORT=3000 node bin/www`

**Comment by davidgatti** [comment]
aa 💩I'm thinking Linux again :D I have no idea if you can do PORT=3000 something something :(

Also you should be able to just type `node bin/www` and node will use a default port from the `www` file.
