### ISSUE TITLE
live stream

### ISSUE THREAD

**Issue by sebmorales** [davidgatti/How-to-Stream-Movies-using-NodeJS#7]
Hi David, 
Thank your for your tutorials, they are really helpful. Not sure if this is the right place but maybe other will also find this question relevant. 

I am trying to stream live content, instead of serving a video file with a known size. Ideally the video could be from a webcam or some other sort of camera. I want the video to stream potentially forever (days or weeks or even months). How can I make this work? 
Thanks!

**Comment by davidgatti** [comment]
I didn't do this but If I had to do I'd try the following

**Option 1**

- save the incoming image from whatever in to a open end file 
- in nodeJS you open that file as read only, the dat will pile up there

when you get a request from the browser you discard the range the video player wants and give it what you have. 

**Option 2**

See if there is a npm module to handle webcams. then check what option do they give you to store the video, ideally you'd want this stream to be saved in memory in to a Buffer (pointless to store it on a drive first), and read the video that from that buffer, while discarding again the range of the Video player.

**Option 3**

Check if the video player have a "live" mode, where it dose not send the range, and will accept any amount of dat you'll send to it. 

I hope this ideas will help, and if you come up with a good solution don't hesitate to share it :)
