### ISSUE TITLE
How i can test it?

### ISSUE THREAD

**Issue by KotsanisNakos** [davidgatti/How-to-Stream-Movies-using-NodeJS#8]
I download your project and install the modules that required. I'm trying to start the server to test it but there is no server :/ how to have a server and then stream through it a URL video? (or a movie)

**Comment by davidgatti** [comment]
I'm sorry but I can't possibly teach you how to work with NodeJS, first learn Node and then try to use the project.

**Comment by KotsanisNakos** [comment]
It's more possible that you don't explain very good how "your??" code run.
I have found solution for rps stream with node and it's milles away from
this. Next time (when the code is yours and not from a documentation) try
to explain better (if its possible for you) what the documentation u copy
says.
